# Generated by Django 5.1 on 2024-11-28 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonprofit', '0003_donatemoney_donatestuff_donationstuffcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donatemoney',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='donatemoney',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nonprofit.organization'),
        ),
        migrations.AddField(
            model_name='donatestuff',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='donatestuff',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nonprofit.organization'),
        ),
    ]
