# Generated by Django 5.1 on 2024-11-28 08:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonprofit', '0004_donatemoney_date_donatemoney_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatemoney',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='donatestuff',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
