# Generated by Django 5.1 on 2024-11-28 08:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonprofit', '0005_alter_donatemoney_date_alter_donatestuff_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatemoney',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='donatestuff',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
