# Generated by Django 5.1 on 2024-11-28 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonprofit', '0007_alter_event_money_donation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='money_donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nonprofit.donatemoney'),
        ),
        migrations.AlterField(
            model_name='event',
            name='stuff_donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nonprofit.donatestuff'),
        ),
    ]
