# Generated by Django 5.1 on 2024-11-28 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonprofit', '0008_alter_event_money_donation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donatestuff',
            name='category',
        ),
        migrations.RemoveField(
            model_name='donatestuff',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='event',
            name='stuff_donation',
        ),
        migrations.DeleteModel(
            name='DonationStuffCategory',
        ),
        migrations.DeleteModel(
            name='DonateStuff',
        ),
    ]
